"""Initial_fresh_start

Revision ID: c3a5d177dbda
Revises: 
Create Date: 2025-12-20 14:38:31.938886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a5d177dbda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('crop_variety', sa.String(length=100), nullable=True),
    sa.Column('scientific_name', sa.String(length=100), nullable=True),
    sa.Column('crop_category', sa.String(length=50), nullable=True),
    sa.Column('optimal_temperature_min', sa.Float(), nullable=True),
    sa.Column('optimal_temperature_max', sa.Float(), nullable=True),
    sa.Column('optimal_rainfall_min', sa.Float(), nullable=True),
    sa.Column('optimal_rainfall_max', sa.Float(), nullable=True),
    sa.Column('soil_type_preference', sa.JSON(), nullable=True),
    sa.Column('ph_range', sa.JSON(), nullable=True),
    sa.Column('growing_season', sa.String(length=50), nullable=True),
    sa.Column('sowing_time', sa.JSON(), nullable=True),
    sa.Column('harvesting_time', sa.JSON(), nullable=True),
    sa.Column('growth_duration', sa.Integer(), nullable=True),
    sa.Column('expected_yield_min', sa.Float(), nullable=True),
    sa.Column('expected_yield_max', sa.Float(), nullable=True),
    sa.Column('market_price_range', sa.JSON(), nullable=True),
    sa.Column('cost_of_cultivation', sa.Float(), nullable=True),
    sa.Column('common_diseases', sa.JSON(), nullable=True),
    sa.Column('common_pests', sa.JSON(), nullable=True),
    sa.Column('disease_management', sa.Text(), nullable=True),
    sa.Column('pest_management', sa.Text(), nullable=True),
    sa.Column('irrigation_schedule', sa.JSON(), nullable=True),
    sa.Column('fertilizer_recommendations', sa.JSON(), nullable=True),
    sa.Column('pesticide_recommendations', sa.JSON(), nullable=True),
    sa.Column('suitable_regions', sa.JSON(), nullable=True),
    sa.Column('current_season_status', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_data_id'), 'crop_data', ['id'], unique=False)
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('scheme_name', sa.String(length=200), nullable=True),
    sa.Column('scheme_details', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('application_process', sa.Text(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('contact_information', sa.JSON(), nullable=True),
    sa.Column('target_beneficiaries', sa.String(length=200), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('loan_amount_min', sa.Float(), nullable=True),
    sa.Column('loan_amount_max', sa.Float(), nullable=True),
    sa.Column('repayment_period', sa.String(length=50), nullable=True),
    sa.Column('subsidy_percentage', sa.Float(), nullable=True),
    sa.Column('subsidy_amount_max', sa.Float(), nullable=True),
    sa.Column('crop_name', sa.String(length=100), nullable=True),
    sa.Column('mandi_name', sa.String(length=100), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('modal_price', sa.Float(), nullable=True),
    sa.Column('arrival_quantity', sa.Float(), nullable=True),
    sa.Column('insurance_scheme', sa.String(length=100), nullable=True),
    sa.Column('premium_rate', sa.Float(), nullable=True),
    sa.Column('sum_insured', sa.Float(), nullable=True),
    sa.Column('coverage_period', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_data_crop_name'), 'financial_data', ['crop_name'], unique=False)
    op.create_index(op.f('ix_financial_data_data_type'), 'financial_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_financial_data_district'), 'financial_data', ['district'], unique=False)
    op.create_index(op.f('ix_financial_data_id'), 'financial_data', ['id'], unique=False)
    op.create_index(op.f('ix_financial_data_loan_type'), 'financial_data', ['loan_type'], unique=False)
    op.create_index(op.f('ix_financial_data_state'), 'financial_data', ['state'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('preferred_crops', sa.Text(), nullable=True),
    sa.Column('farm_size', sa.String(length=50), nullable=True),
    sa.Column('irrigation_type', sa.String(length=50), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('offline_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=10), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('rainfall_probability', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('evapotranspiration', sa.Float(), nullable=True),
    sa.Column('heat_index', sa.Float(), nullable=True),
    sa.Column('forecast_days', sa.Integer(), nullable=True),
    sa.Column('forecast_data', sa.JSON(), nullable=True),
    sa.Column('weather_alerts', sa.JSON(), nullable=True),
    sa.Column('agricultural_alerts', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('query_language', sa.String(length=10), nullable=True),
    sa.Column('input_type', sa.String(length=20), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('weather_conditions', sa.JSON(), nullable=True),
    sa.Column('crop_context', sa.JSON(), nullable=True),
    sa.Column('processing_time', sa.String(length=20), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_id'), 'queries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_financial_data_state'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_loan_type'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_id'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_district'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_data_type'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_crop_name'), table_name='financial_data')
    op.drop_table('financial_data')
    op.drop_index(op.f('ix_crop_data_id'), table_name='crop_data')
    op.drop_table('crop_data')
    # ### end Alembic commands ###
